### ISSUE TITLE
能否添加某种标示来表示现在的时间进度？

### ISSUE THREAD

**Issue by MeiK2333** [dreamerblue/recent_contests#2]
![image](https://user-images.githubusercontent.com/20951666/53288275-87519f80-37c1-11e9-9836-1b904c621608.png)

如图，现在的所有条目都是白板一张，很难确定当前时间进度到哪了。

可以标示一下当前进度，比如对正在进行中的以某种颜色填充，即将到来的用某种颜色等等。

**Comment by MeiK2333** [comment]
进行中的比赛用背景色显示个进度条如何？

**Comment by dreamerblue** [comment]
1.0.6 已添加。
